[project]
name = "hep_workflows"
dynamic = ["version"]
dependencies = [
    "law==0.1.20",
    "luigi==3.5.1",
    "numpy",
    "python-dateutil",
    "tqdm==4.66.3"
]

[tool.setuptools.packages.find]
include = ["hep_workflows*"]

[tool.setuptools.package-data]
hep_workflows = ["*.sh", "bin/*", "resources/**/*"]